# autogenerated by txs
#include:calc
#include:xkeyval
\addtocounter#S
\addtolength#S
\adjaddtocounter#S
\adjaddtocounter{arg1}{arg2}#S
\adjaddtolength#S
\adjaddtolength{arg1}#S
\adjcalcset#S
\adjsetcounter#S
\adjsetcounter{arg1}{arg2}#S
\adjsetlength#S
\adjsetlengthdefault#S
\pgfmathpostparse#S
\setcounter#S
\setlength#S
