# autogenerated by txs
#include:float
#include:ifthen
\listalgorithmname#S
\listofalgorithms#S
\begin{algorithm*}
\begin{algorithm}
\end{algorithm*}
\end{algorithm}
\equal#S
\isodd#S
\isundefined#S
\lengthtest#S
\thealgorithm#S
