# autogenerated by txs
\AfterLastShipout#S
\AtEndAfterFileList#S
\AtEndDocument#S
\AtVeryEndDocument#S
\AtVeryVeryEnd#S
\BeforeClearDocument#S
\bibcite#S
\clearpage#S
\csname#S
\expandafter#S
\global#S
\makelabels#S
\newlabel#S
\protect#S
\x#S
