# autogenerated by txs
\filedate#S
\fileversion#S
\U/bbm/bx/n#S
\U/bbm/m/n#S
\U/bbmss/bx/n#S
\U/bbmss/m/n#S
\U/bbmtt/m/n#S
\mathbbm #S
\mathbbm#S
\mathbbmss #S
\mathbbmss#S
\mathbbmtt #S
\mathbbmtt#S
