# autogenerated by txs
\applyto{arg1}{arg2}{arg3}#S
\defaction{arg1}{arg2}{arg3}#S
\defpattern{arg1}#S
\doaction{arg1}#S
\erroraction{arg1}#S
\failure{arg1}{arg2}#S
\gobble{arg1}#S
\success{arg1}{arg2}#S
\temp#S
\xcs{arg1}{arg2}#S
