# autogenerated by txs
#include:infwarerr
#include:kvdefinekeys
\AppendGraphicsExtensions#S
\PrependGraphicsExtensions#S
\PrintGraphicsExtensions#S
\RemoveGraphicsExtensions{arg1}#S
\csname#S
\empty#S
\expandafter#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
