# autogenerated by txs
#include:graphics
#include:ifpdf
#include:ifxetex
#include:kvoptions
#include:pdftexcmds
#include:stringenc
\IfFileExists#S
\expandafter#S
\grffilesetup#S
\noexpand#S
\next#S
\x#S
