# autogenerated by txs
\BreakableBackslash#S
\BreakableColon#S
\BreakableHyphen#S
\BreakablePeriod#S
\BreakableSlash#S
\BreakableUnderscore#S
\_#S
\bshyp#S
\colonhyp#S
\dothyp#S
\fshyp#S
\hyp#S
\nhttfamily#S
\nohyphens{arg1}#S
\touchextrattfonts#S
\touchttfonts#S
\bshyp #S
\colonhyp #S
\dothyp #S
\fshyp #S
\hyp #S
\nhttfamily #S
\textnhtt #S
\textnhtt#S
