# autogenerated by txs
#include:etexcmds
#include:infwarerr
\csname#S
\empty#S
\expandafter#S
\ifincsname#S
\kvsetkeys{arg1}{arg2}#S
\kvsetknownkeys#S
\noexpand#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
