# autogenerated by txs
#include:ltxcmds
#include:pdftexcmds
\EdefEscapeHex{arg1}{arg2}#S
\EdefEscapeName{arg1}{arg2}#S
\EdefEscapeString{arg1}{arg2}#S
\EdefSanitize{arg1}{arg2}#S
\EdefUnescapeHex{arg1}{arg2}#S
\EdefUnescapeName{arg1}{arg2}#S
\EdefUnescapeString{arg1}{arg2}#S
\empty#S
\expandafter#S
\expandafter{arg1}#S
\noexpand#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
