# autogenerated by txs
#include:ifluatex
#include:ifpdf
#include:infwarerr
#include:ltxcmds
#include:luatex-loader
\csname#S
\empty#S
\expandafter#S
\pdfdraftmode#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
\y#S
\z#S
y#S
