# autogenerated by txs
\begin{description}#S
\deschook#S
\end{description}#S
\enumerate#S
\enumhook#S
\enumhooki#S
\enumhookii#S
\enumhookiii#S
\enumhookiv#S
\itemhook#S
\itemhooki#S
\itemhookii#S
\itemhookiii#S
\itemhookiv#S
\itemize#S
\makelabel#S
