# autogenerated by txs
#include:bigintcalc
#include:infwarerr
\csname#S
\empty#S
\expandafter#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
\UniqueCounterCall#S
\UniqueCounterGet#S
\UniqueCounterIncrement#S
\UniqueCounterNew#S
