# All SpaceVim option below [option] section, in context of layers loaded by default.

[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer

  # Core layer

  colorscheme = "material"
  colorscheme_bg = "dark"

  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  sidebar_width = 20
  enable_tabline_ft_icon = 1

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts

  disabled_plugins = ["neosnippet-snippets", "vim-snippets", "vim-surround"]
  vimcompatible = true

  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true

#guifont = "SauceCodePro Nerd Font Mono:h15"
  automatic_update = true
  bootstrap_after = "myconfig#after"
  bootstrap_before = "myconfig#before"

  filemanager = "nerdtree"
  enable_filetree_gitstatus = true
  filetree_direction = "left"

  # autocomplete layer options
  autocomplete_method = "coc"  # also provides lsp features, so no need to enable 'lsp' layer

  snippet_engine = "ultisnips"

  # Show only files editable by vim
  wildignore='*.pyc,*.o,*.obj,*.svn,*.swp,*.class,*.hg,*.DS_Store,*.min.*,*.tmp,*.toc,*.aux,*.log,*.bbl,*.blg,*.log,*.lof,*.lot,*.ilg,*.out,*.glo,*.gls,*.nlo,*.nls,*.brf,*.ist,*.glg,*.synctex.gz,*.tgz,*.idx,*.ind,*blx.bib,*.fdb_latexmk,*.run.xml,*.bcf,*.glsdefs,*.fls,*.eps,*.pdf,*.png,*.jpg'



# Call private layers and specify options below ==============================================================

[[layers]]
  name = "autocomplete"
  auto_completion_enable_snippets_in_popup = true
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "ui"
  enable_sidebar = false
  enable_scrollbar = false
  enable_indentline = true
  indentline_char = '|'
  enable_cursorword = true
  conceallevel = 1
  concealcursor = ''
  cursorword_delay = 50
  cursorword_exclude_filetype = []
  indentline_exclude_filetype = []


[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#python"
  # enabled_linters = ['python', 'pylint']
  # python_interpreter = '/usr/bin/env/python3'

[[layers]]
  name = "lang#html"

[[layers]]
  name = "git"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 10

[[layers]]
  name = "incsearch"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[layers]]
  name = "fzf"

# Custom Plugins ==============================================================

[[custom_plugins]]
  name = "vim-python/python-syntax"
  merged = false

[[custom_plugins]]
  name="ryanoasis/vim-devicons"
  merged = false

[[custom_plugins]]
  name="machakann/vim-sandwich"
  merged = false

[[custom_plugins]]
  name="907th/vim-auto-save"
  merged = false

[[custom_plugins]]
  name="tpope/vim-obsession"
  merged = false

[[custom_plugins]]
  name="kaicataldo/material.vim"
  branch='main'
  merged = false

[[custom_plugins]]
  name="jpalardy/vim-slime"
  branch='main'
  merged = false

