require("impatient") -- Improves Startup Performance
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.whichkey")
require("user.cmp")
require("user.lsp")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.indentline")
require("user.alpha")
require("user.lualine")
require("user.material")
require("user.autosave")
require("user.remember")
require("user.slime")
require("user.vimtex")
require("user.ultisnips")
require("user.clever")  -- Improve f, F, t, T line searches
